### ISSUE TITLE
Stickers not usable

### ISSUE THREAD

**Issue by HungryBoy02** [apsun/uSticker#10]
Stickers have been working just fine, but now when I add new ones, they don't work, this is similar to your previous issue, please fix it, I love this app

**Comment by apsun** [comment]
As mentioned in the release notes, you need to update past 8.1.7. [8.2.7](https://www.apkmirror.com/apk/google-inc/gboard/gboard-8-2-7-246545876-release/) works just fine for me.

**Comment by HungryBoy02** [comment]
On the play store, the only available version is 1.5.0

**Comment by HungryBoy02** [comment]
Also I'm on a Google pixel 2 xl running Android 9

**Comment by apsun** [comment]
I am referring to the Gboard version. This is a bug in Gboard, not uSticker.

**Comment by HungryBoy02** [comment]
Yeah I just realized, either way though, the only available version of Gboard (for my device at least) is 8.1.7

**Comment by HungryBoy02** [comment]
I joined the Gboard beta and I am assuming that that will fix the issue
