### ISSUE TITLE
'Indexable is 55117 bytes, which is larger than the maximum allowed size of 30000 bytes'

### ISSUE THREAD

**Issue by increpare** [apsun/uSticker#11]
I tried to add a bunch of images from this directory http://ded.increpare.com/~locus/words_en.zip and got this error in app

```
com.google.firebase.appindexing.zza: Indexable is 55117 bytes, which is larger than the maximum allowed size of 30000 bytes The invalid indexable url is: usticker://sticker/en/output_en
	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.dispatchTransaction(Unknown Source:19)
	at com.google.android.gms.internal.base.zab.onTransact(Unknown Source:3)
	at android.os.Binder.execTransact(Binder.java:739)
```

One suspects it's because it's because I'm trying to add >1k stickers... (or maybe with too many tags? Dunno!)

**Comment by apsun** [comment]
Yeah this basically means you have too many stickers in one directory, and/or the sticker filenames are too long. You can either split them into multiple directories, or rename the files to something shorter.

**Comment by increpare** [comment]
Ooh splitting them into directories!  Given that I'm generating them in a script anyway, that's easy peasy :)  And to think I had just gotten the code to compile/run on my phone, and was figuring out how to badly write Kotlin :P

Thanks for the speedy reply, and the nice software :)
