### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by kmanxhuka** [apsun/uSticker#15]
the app crashes when I try to import any stickers, or when I try to select any location. Either options I touch, it just crashes.

I'm using Android 9, LineageOS based rom.

**Comment by apsun** [comment]
Mind posting a logcat dump here? Thanks. The only reason I could imagine both of those buttons failing is that you don't have a storage browser app installed on your phone. If you've disabled the built in one, can you try enabling it?

**Comment by kmanxhuka** [comment]
> Mind posting a logcat dump here? Thanks. The only reason I could imagine both of those buttons failing is that you don't have a storage browser app installed on your phone. If you've disabled the built in one, can you try enabling it?

I had a storage browser, but not the built in one, so after I enabled it, the app worked fine.
There is another issue I found it weird. When importing png stickers on gboard, some of it are sent as stickers, but some other ones are sent as photos, even when all of it are png format.
thanks (should I open a new issue for the last issue?)

**Comment by apsun** [comment]
Thanks for confirming. uSticker requires an app that supports the ACTION_OPEN_DOCUMENT_TREE intent. I would suggest submitting a feature request to the developer of your file browser app for them to support it. I'll also add some logic to not crash but gracefully fail if such an app doesn't exist.

Can you explain what you mean by 'sticker' vs. 'photo'? uSticker does not distinguish between the two, so it would depend on what app you're using to send them. Signal, for example, sends everything as a photo.

**Comment by apsun** [comment]
Fixed crash in commit 775cf76570b4a7990491c6f397c6b0bff7e74f93.
