### ISSUE TITLE
Can't locate sticker folder.

### ISSUE THREAD

**Issue by ChadwickFenwick** [apsun/uSticker#16]
Howdy,

It was working fine yesterday but now it doesn't show my folder in the selection on top. Tried to add it again and restart but still doesn't show up.

App is great!

**Comment by apsun** [comment]
Can you explain in a bit more detail? Are you saying the import works, but nothing shows up in Gboard? Or does the import fail?

If the import works but Gboard doesn't show them, I get this occasionally too, usually a restart of the device fixes it. If not please post your Gboard version and I'll investigate.

**Comment by ChadwickFenwick** [comment]
Yes, it imports them fine, a popup says that # was added. GBoard doesn't show the folder in the carousel on top when searching for the GIFs, but it shows random ones that I didn't add. I also tried to restart/install and no worky. Who knows...

GBoard version is: 8.8.10.277552084-release-arm64-v8a

**Comment by apsun** [comment]
Interesting, I have the same version and it works fine for me. Would you mind grabbing a logcat that includes importing the stickers and opening up the Gboard sticker view? Thanks!

**Comment by ChadwickFenwick** [comment]
Odd, now it seems to be working?!?! Didn't change or do anything but now the folder is showing up. Really weird. Might be the Pixel 3 or something odd happening.

**Comment by apsun** [comment]
Yeah, Gboard does that sometimes :-/

It might be asynchronously refreshing the index in the background or something. Sadly I can't do anything about this, it's on Google's end to fix. Since there's nothing to fix on the uSticker side I'll close this issue, but thanks for reporting!
