### ISSUE TITLE
Some sticker are sent as images

### ISSUE THREAD

**Issue by lucatarik** [apsun/uSticker#17]
Hi, i'm resizing all the sticker with the same options, but some of them are currently managed as images on whatsapp and instagram

https://gofile.io/?c=2VuD7W

**Comment by apsun** [comment]
What do you mean? Can you upload a screenshot of what you expect, and what you actually get? uSticker does not have any logic related to this afaik, so it would be on the WhatsApp/IG side.

**Comment by lucatarik** [comment]
Correct behavior:
https://i.imgur.com/t3Ydhux.png
Flawled one: 
https://i.imgur.com/vuFZNkW.png

it sends the sticker as a photo and not as a sticker.
I've more than 600 sticker and it happens only to almost 10.
i tried to rename them, edit them, but the result is the same

all images are 512x512 px png 256 colors

**Comment by lucatarik** [comment]
made a video to make it clearer
https://streamable.com/ov3fb

**Comment by apsun** [comment]
Hmm I don't use WhatsApp, but maybe it's related to transparency in the images? (The ones that were sent as stickers had no background) Or maybe jpg vs. png?

**Comment by lucatarik** [comment]
they are all png made with imagemagick and these options
convert $filen -trim +repage -resize 512x512 -gravity center -background transparent -extent 512x512  $filen
pngquant --ext .png --quality=65-80 --force -v 256 --speed 1 --strip $filen

but now I'm sure that the bug is within whatsapp and it's not usticker! ty
