### ISSUE TITLE
Whatsapp issue

### ISSUE THREAD

**Issue by ShinsuSenju** [apsun/uSticker#33]
The sticker is getting send as an image in whatsapp

--- 

App version: 1.5.3 (14) 
Gboard version: 9.1.8.300404574-release-armeabi-v7a (26910825) 
Android version: 6.0 (API23)

**Comment by apsun** [comment]
This is not the responsibility of uSticker, whether the sticker is sent as an image is determined by the app you're sending it in. You should submit a bug report to WhatsApp.
