### ISSUE TITLE
uSticker

### ISSUE THREAD

**Issue by Theodns** [apsun/uSticker#43]
Buenas, estoy teniendo problemas a la hora de acceder a la app sticker ya que cada vez que trato de abrir el apartado de <Import Sticker to gboard> obtengo este mensaje "Cannot find an app that supports ACTION_OPEN_DOCUMENT_TREE. If you disabled the built-in Android file browser, please re-enable it to use uSticker". Qué debería hacer en esta situación?? 

Muchas gracias y buen gusto

**Comment by apsun** [comment]
Usually this happens on custom ROMs where there are no file browser apps installed. I would recommend one, but I don't know which ones actually support ACTION_OPEN_DOCUMENT_TREE. All of the phones I've used came with one of these apps preinstalled :/
