### ISSUE TITLE
Can't add more than 1 pack. 

### ISSUE THREAD

**Issue by jedimindticks** [apsun/uSticker#44]
open can't add more than 1 pack, if i add another set of 100, it just overwrites the previous pack. tried changing directories doesn't work.

**Comment by apsun** [comment]
To add new packs, you don't change the directory; you create a new directory inside the current one (and hit import again). Every sub-directory within the one you selected turns into a new sticker pack.

**Comment by jedimindticks** [comment]
doesn't work, that's what I'm saying. no matter if i select different sub-directories, it still constantly overwrites the previous pack.
Didn't change the directory, imported from different sub-directories. check the attached screenshot, it just overwrites everything. 
![Screenshot_20201118-190206926](https://user-images.githubusercontent.com/74632504/99536639-a437f880-29d0-11eb-8f26-e743a46d9e56.jpg)
![Screenshot_20201118-190232327](https://user-images.githubusercontent.com/74632504/99536660-a8fcac80-29d0-11eb-8469-34ba50daec79.jpg)

**Comment by apsun** [comment]
What I meant was to keep the parent directory selected. So for example, if you have:

```
Pictures/Stickers/
  PackA/
   1.jpg
   2.jpg
  PackB/
   3.jpg
```

Then in uSticker, you should select `Pictures/Stickers/`.
