### ISSUE TITLE
Request: import stickers from other keyboards within the app

### ISSUE THREAD

**Issue by Efreak** [apsun/uSticker#48]
Is there any chance you'll allow importing stickers from other sticker packs by providing an input field within the app that grabs them? I'd like to move some stickers from other rarely-used sticker packs to make them easier to find. For example, specific web searches, emoji mashups, and (if possible) stickers from other keyboards (samsung keyboard and others have their own sticker packs that don't work with gboard). Some of these, like the emoji mashups, can't be obtained at all, while others (gboard sticker packs) would require extracting resources from the app.

**Comment by apsun** [comment]
This seems pretty straightforward to implement as a standalone app (just have a textbox that writes the images to external storage, and then use uSticker to import that directory). There also isn't any existing "infrastructure" in uSticker like handling images, writing files, etc that you could take advantage of to make this any easier than just making it as a separate app, so I would recommend going that route instead.

Also unfortunately I don't take feature requests for uSticker (this is mainly just to keep myself sane with commitments), sorry :-(
