### ISSUE TITLE
Webp Image Support

### ISSUE THREAD

**Issue by FredHappyface** [apsun/uSticker#5]
Hi, was wondering if gboard supports .webp images as I cannot find anything online on what image formats are supported and was wondering if you know or can point me in the right direction

**Comment by apsun** [comment]
Not sure. uSticker limits the file types it looks for to prevent non-images from being added and failing to load. I can give webp a try later if I have some free time.

**Comment by FredHappyface** [comment]
That'd be great if you can, thanks - I ask because of the WhatsApp using gboard's stickers feature which has been in the news.

**Comment by apsun** [comment]
It seems that webp works fine in Gboard, I'll add it to the list of supported file types.

**Comment by apsun** [comment]
Note that animated webp doesn't work - same as animated png. Currently the only format that supports animations in Gboard seems to be gif.
