### ISSUE TITLE
Reimporting stickers with same filename does not work

### ISSUE THREAD

**Issue by huhehuhehu** [apsun/uSticker#50]
uSticker version: 1.6.0 (16) 
Gboard version: 10.1.04.342850159-release-arm64-v8a (44340022) 
Android version: 11 (API30)

So when I made modifications to an image and pushing the import button, it will not change the existing one.
Here is what I've tried:
1. Simply copy pasting to replace the existing file in the directory -> import (will use the old image)
2. Deleting the file -> import -> add file -> import (will reuse the old file)
3. Change import directory -> import -> change back to original directory -> import (will reuse old file)
So the only thing that will work is to actually create a new folder and basically do an initial import again.

**Comment by apsun** [comment]
This is a Gboard issue sadly, they cache the sticker images and there's no way to tell it to invalidate them (it's a reasonable design since normally stickers are not expected to change, but doesn't work great for uSticker). Can you try clearing the Gboard cache in settings and try again?

**Comment by huhehuhehu** [comment]
Ah I see. Yea ok makes sense. Thanks!
