### ISSUE TITLE
Can't downgrade System installed GBoard

### ISSUE THREAD

**Issue by ghost** [apsun/uSticker#54]
Hi Developer, 
In my old device I used to Install GBoard 10.1.04 and use uSticker. But after in my new device, the GBoard comes pre installed with Version 10.3, I cannot downgrade to lower version, nor cannot uninstall and Install a older version, since it is a system. 

I that case how can I use uSticker, is there any other keyboard application that supports uSticker ? Any help would be appreciated, thank you.

**Comment by apsun** [comment]
I suppose you could grab a 10.1 APK, change the package name, and re-sign it with your own key. I don't know off the top of my head how to do that, though. I think apktool could do this. You would have two copies of Gboard, but you can just disable the system one.

**Comment by ghost** [comment]
Thank you for the Suggestion
