### ISSUE TITLE
WebP Image Sharing

### ISSUE THREAD

**Issue by FredHappyface** [apsun/uSticker#6]
Hello, 

It seems that when selecting a webp image through gboard, a more general share your is shown. For example, in WhatsApp rather than showing the image preview along with the send button. A list of recent chats is shown.

I'm aware this may be a quirk of gboard. I thought I should just let you know about this.

If you need screenshots or other information let me know.

Thanks - Love using your app!

**Comment by apsun** [comment]
I would say it's probably an issue with WhatsApp, unfortunately this behavior is out my of control.

**Comment by FredHappyface** [comment]
Fair enough. Just so you know a similar thing happens in signal. Thanks anyway 😊

**Comment by apsun** [comment]
Interesting, WebP is not a commonly supported image type after all (in fact this is the first time I've heard of it, previously I only knew about WebM). In the case of Signal, you can see that [they only support JPG, PNG, and GIF](https://github.com/signalapp/Signal-Android/blob/be215b3b1e7e5751d1a2317cf6d77c5ae79fb9ac/src/org/thoughtcrime/securesms/components/ComposeText.java#L145). Thanks for reporting though :-)
