### ISSUE TITLE
Black background added to transparent images

### ISSUE THREAD

**Issue by ChrisManuel86** [apsun/uSticker#7]
I'm not sure if this would be a bug caused by the indexing of the pictures or [the] messages [app] in general. 
I've tested sending the raw .png files and found no issue, but it seems that when if an image with transparency is sent, a black background is added to the image. (see image below)

![message-usticker-bug](https://user-images.githubusercontent.com/27974680/52888236-d3507480-312f-11e9-98a4-65163391e8aa.png)

This was tested on using both .webp format and .png format. Images were resized and converted using GIMP 2.10

**Comment by apsun** [comment]
uSticker performs no image manipulation whatsoever, it just serves files from your filesystem for Gboard to see. So this would either be an issue with Gboard or that app that you are sending the stickers with. I'm pretty sure I've sent transparent stickers in Signal before (not that it's really useful), so I'm inclined to believe it's a messages thing. Have you tried using a different app?

**Comment by ChrisManuel86** [comment]
Ah, okay. It might be an issue with Gboard or (Android) Messages then.

I've done some additional testing, only sending one sticker at a time, and the issue doesn't seem to occur. However, if multiple stickers are sent at the same time, and the message is converted to an MMS, then the black background is added in place of the transparent one.

I haven't tried any other apps, but will begin testing this soon, and report back my findings.

I guess one more thing to note, is that this does not happen when sending any of the "selfie" stickers that can be created and sent via Gboard.

**Comment by ChrisManuel86** [comment]
So after doing some additional testing in the (Facebook) Messenger app as well as Discord, it seems to be an issue stemming from (Android) Messages. I apologize about bringing this issue up to you 😣 But I appreciate the prompt response and willingness to help out with the issue! 10/10 would rate the app 5 stars again!

**Comment by apsun** [comment]
No worries, glad to help :-)
